extjs_generate_model:
    path:  /generateModel.js
    defaults: { _controller: TpgExtjsBundle:Generator:generateModel }

extjs_remote_api:
    path:  /remoteapi.js
    defaults: { _controller: TpgExtjsBundle:Generator:generateRemoteApi }

extjs_remoting:
    path:  /remoting/{bundle}
    defaults: { _controller: TpgExtjsBundle:Generator:remoting }